version: '3.3'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    working_dir: /var/www/html
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_TABLE_PREFIX: wptl_
      # WP_DEBUG=true
      # WP_DEBUG_DISPLAY=false
      # WP_DEBUG_LOG=true 
    volumes:
      - ./:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - sklearn
    privileged: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - sklearn
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: examplepass 
      UPLOAD_LIMIT: 300M
    networks:
      - sklearn

networks:
  sklearn:
    driver: bridge

volumes:
  db:
    driver: local
    
#sudo docker-compose up -d
#with clear data:  sudo docker-compose down --volumes
#with only down:  sudo docker-compose down